### ISSUE TITLE
Authorship on JOSS paper

### ISSUE THREAD

**Issue by adrn** [adrn/gala#100]
@bsipocz @smoh @syrte 

I've submitted a paper to [JOSS](joss.theoj.org) describing Gala. It's [currently under review](https://github.com/openjournals/joss-reviews/issues/388), and you can read the review and response at the link. Please let me know by 1 Oct if you'd like to be listed as co-authors on the paper, in which case please send me your current affiliation and ORCID.

**Comment by bsipocz** [comment]
Hey @adrn! I can only repeat what I said for other papers in the past, namely while getting on papers is always exciting and a great feedback, I feel this time I didn't do enough with the mere 8 commits. It's just not fair towards others (this time you), who did the actual coding and serious bugfixing.

**Comment by smoh** [comment]
I feel the same way since mine was also miniscule.
