### ISSUE TITLE
astropy-helpers manual update

### ISSUE THREAD

**Issue by bsipocz** [adrn/gala#117]
ah_helpers and ez_setup are also part of the helpers, but the automated updates are not picking up this repo as the submodule has already been updated to v3.2.dev

I would suggest to stick with the 3.1 branch if you plan to receive the auto updates, otherwise it will be always assumed to be up to date (given that 3.2.dev looks a more up to date version than 3.1.whatever release, even though it's not necessarily the case).

**Comment by adrn** [comment]
Ah, got it! Thanks
