### ISSUE TITLE
Re-implement snapshotting for mockstreams

### ISSUE THREAD

**Issue by adrn** [adrn/gala#150]
Once #148 is merged, work on re-implementing support for outputting snapshots of mockstreams during integration.

**Comment by balbinot** [comment]
If I use MockStreamGenerator.run() with the nbody option, I get a shaped broadcast mismatch in the HDF5 file.

`
gen_jhelum = ms.MockStreamGenerator(df, mw, progenitor_potential=jpot)
jhelum_stream, _ = gen_jhelum.run(w0, jmass, dt=-1 * u.Myr, n_steps=4000, nbody=unn, release_every=4, output_every=1,
                                  output_filename='Jhelum_massive_sag.hdf5', check_filesize=False, overwrite=True)
`

Produces 

`~/anaconda3/lib/python3.7/site-packages/h5py/_hl/selections.py in broadcast(self, target_shape)
    297                     tshape.append(t)
    298                 else:
--> 299                     raise TypeError("Can't broadcast %s -> %s" % (target_shape, count))
    300         tshape.reverse()
    301         tshape = tuple(tshape)

TypeError: Can't broadcast (3, 4) -> (3, 1, 2)`

**Comment by adrn** [comment]
Thanks @balbinot! I'll take a look
