### ISSUE TITLE
Segfault and core dump on manipulating hessians

### ISSUE THREAD

**Issue by smoh** [adrn/gala#159]
python 3.7
gala, numpy versions: 1.0, 1.16.4

I get core dump / seg fault from doing the follwing:
```python
import astropy.units as u
from gala.potential import BovyMWPotential2014

BovyMWPotential2014().hessian([[0, 8, 0]]*u.kpc)
```
Tracebacks: https://gist.github.com/smoh/0e803684b14d87bba4a97e5bb3e33bb0
1.out: beginning of errors from Red Hat
2.out: full traceback from Mac OSX 10.14.4

In both I did fresh install with conda
```sh
conda create -n gala-test
conda install -c conda-forge astro-gala
```
Any ideas?

**Comment by adrn** [comment]
```python
pot['disk'].hessian([[0, 8, 0]]*u.kpc)
pot['halo'].hessian([[0, 8, 0]]*u.kpc)
```
are ok but 
```python
pot['bulge'].hessian([[0, 8, 0]]*u.kpc)
```
fails.

It looks like I never implemented the hessian for `PowerLawCutoffPotential`: https://github.com/adrn/gala/blob/master/gala/potential/potential/builtin/builtin_potentials.c#L396

**Comment by adrn** [comment]
Oh, and BTW: passing in `[[0, 8, 0]]*u.kpc` will error sometimes because the function is expecting something that has shape `(3, ...)` not `(..., 3)`.

**Comment by smoh** [comment]
Yea, that makes sense. I see -- that shape information was what I was trying to figure out by just poking around trying..!

**Comment by adrn** [comment]
Ah, right, with the complication that it was doomed to fail even with the correct shape :) 

Of course, if you feel like implementing the Hessian ... 😉- it only involves derivatives of the incomplete gamma function! 

If you just need a rough MW Hessian, you can use the `MilkyWayPotential` instead. But it looks like I also haven't implemented the Hessian for a flattened NFW 😭🔫...so you have to do, e.g.,:
```python
from gala.potential import MilkyWayPotential
pot = MilkyWayPotential(halo=dict(c=1.)) # make it spherical
pot.hessian([0, 8., 0] * u.kpc)
```

**Comment by smoh** [comment]
Thanks! Yes, I'll have a look to see if I can fix this later this week if it's still open.
