### ISSUE TITLE
GreatCircleICRSFrame does not align with given pole?

### ISSUE THREAD

**Issue by ahriley** [adrn/gala#160]
python 3.7.3
gala, astropy versions: 1.0, 3.2.1

Noticed this when I was working today:

```python
import numpy as np
import matplotlib.pyplot as plt
from gala.coordinates import GreatCircleICRSFrame
import astropy.units as u
import astropy.coordinates as coord

pole = coord.SkyCoord(ra=32.5, dec=19.8, unit='deg')
gcfr = GreatCircleICRSFrame(pole=pole)
gc = coord.SkyCoord(phi1=np.linspace(0,360,100), phi2=0, unit='deg', frame=gcfr)

gc = gc.transform_to(coord.ICRS)
sep = pole.separation(gc)
plt.plot(gc.ra, sep, '.')
```

![test](https://user-images.githubusercontent.com/30327239/63977502-9fa8bc80-ca79-11e9-8916-666beb1dc6d3.png)

If a great circle is generated from a pole, shouldn't all points along the circle be 90 degrees from the pole? In other words, shouldn't the pole be located at `phi2 = 90`?

```python
pole_eff = GreatCircleICRSFrame(phi1=20*u.deg, phi2=90*u.deg, pole=pole)
pole_eff = pole_eff.transform_to(coord.ICRS)
print(pole_eff.ra.deg, pole_eff.dec.deg)
32.50000000000001 70.2
```

Looks like the RA is preserved fine but the DEC is `90 - pole_dec`? Is this intentional (and if so is it documented somewhere)?

**Comment by adrn** [comment]
That looks suspicious - I'll take a look, thanks for the issue!

**Comment by adrn** [comment]
Looks like this is a bug! This only seems to be a problem when `ra0` is not provided, i.e.:
```python
pole = coord.SkyCoord(ra=32.5, dec=19.8, unit='deg')
gcfr = GreatCircleICRSFrame(pole=pole, ra0=0*u.deg)
gc = coord.SkyCoord(phi1=np.linspace(0,360,100), 
                    phi2=0, 
                    unit='deg', frame=gcfr)
gc = gc.transform_to(coord.ICRS)
sep = pole.separation(gc)
plt.plot(gc.ra, sep, '.')
```
![image](https://user-images.githubusercontent.com/583379/64122343-586b4600-cd6f-11e9-92f3-28132556ace3.png)

Pull request with a fix incoming...

**Comment by ahriley** [comment]
Great! It does look like providing an `ra0` fixes most of the cases I was looking at.

This may or may not be a related issue, but when the pole's `dec=0` then other weirdness is going on

```python
pole = coord.SkyCoord(ra=32.5, dec=0, unit='deg')
gcfr = GreatCircleICRSFrame(pole=pole, ra0=0*u.deg)
gc = coord.SkyCoord(phi1=np.linspace(0,360,100),
                    phi2=0,
                    unit='deg', frame=gcfr)
gc = gc.transform_to(coord.ICRS)
sep = pole.separation(gc)
plt.plot(gc.ra, sep, '.')
```

![test](https://user-images.githubusercontent.com/30327239/64126274-cd8c4a80-cd72-11e9-9df0-e7844e9ad051.png)

Here, the `gc` points should be at either `pole_ra + 90` or `pole_ra - 90` and spread around in DEC, but instead

**Comment by adrn** [comment]
Yes, thanks, there is another bug when dec=0 and `ra0` is supplied. I think it's actually not possible to satisfy both `ra0` and the `pole` when `dec=0`, so I've added a warning when this kind of input is passed in that the `ra0` is ignored.
