### ISSUE TITLE
Missing Mockstream on Installation?

### ISSUE THREAD

**Issue by jjensen4571** [adrn/gala#167]
Hi all,

I have been running through the documentation on gala and am interested in creating a mock tidal stream. However, the code below (from the documentation) gives an error. I have checked that all my dependencies are up to date - not sure what could be the issue? Other functions with orbit projections work fine. Let me know if there is something I am missing.

![Screen Shot 2020-01-22 at 13 59 42](https://user-images.githubusercontent.com/44014199/72938450-d8467c80-3d1f-11ea-966e-38a5a221bcf2.png)

**Comment by adrn** [comment]
Hi @jjensen4571 - did you find a solution for this? I haven't had a chance to look in to this yet, but am interested to know what happened!

**Comment by jjensen4571** [comment]
I had to install the development version instead (v1.1dev). My problem was actually that pip was not liked to conda and thus gala was not being properly installed
