### ISSUE TITLE
transform_pm_cov and GreatCircleICRSFrame

### ISSUE THREAD

**Issue by HNLala** [adrn/gala#172]
After instantiating a `GreatCircleICRSFrame`, the astropy function `transform_to` works as expected and transforms given `SkyCoord` coordinates to the new frame defined in `GreatCircleICRSFrame`.

However, `gala.coordinates.transform_pm_cov` doesn't seem to work. When the custom `GreatCircleICRSFrame` is passed as the `to_frame` argument to` transform_pm_cov`, it throws an error caused by:
`coord.frame_transform_graph.find_shortest_path(frame.__class__,  GreatCircleICRSFrame)`

I tried using the same `SkyCoord` object with `transform_pm_cov` while converting to Galactic coordinates (`astropy.coordinates.Galactic`) and it works fine. The attached jupyter notebook reproduces this problem.

[notebook.zip](https://github.com/adrn/gala/files/4582401/notebook.zip)

**Comment by adrn** [comment]
Sorry for the delay. Thanks, yes, this is a real bug!

**Comment by adrn** [comment]
FYI @HNLala - this should now be fixed in the development version. You can install with:
`pip install git+https://github.com/adrn/gala`

**Comment by HNLala** [comment]
Thanks a lot. It works now.
