### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by jortiz12** [adrn/gala#251]
Dear Community
I´m having some when installing issues.
When running the recommended way to install gala, `!python -m pip install gala`, I get various errors and warnings.

![imagen](https://user-images.githubusercontent.com/2719866/139954904-cf2b68b7-e530-41e3-9302-76d57af4a94b.png)

I suspect thsis is the reason why I get errors when running imports such as

![imagen](https://user-images.githubusercontent.com/2719866/139954944-5801e007-431d-4a14-bed9-19a6d6145d65.png)
![imagen](https://user-images.githubusercontent.com/2719866/139955016-3e7179c2-b77a-4a5c-8f68-85498de00958.png)

Thanks in advance

**Comment by adrn** [comment]
Asked via email:

> Just wanted, if I may, check with you the following error I get when trying to install astro-gala.
> I´ve tried all the following
> 
> conda install -c conda-forge astro-gala
> conda install -c conda-forge/label/cf201901 astro-gala
> conda install -c conda-forge/label/cf202003 astro-gala,
> 
> , and it seems that no appropriate channel is found.

I recently renamed the pip and conda name of the package to simply "gala" to match the package name, so that is one issue.

Second, it looks like you are building on windows - is that right? One caveat is that I haven't done much testing on windows because I don't have access to a windows machine. But I believe the conda-forge install should work on win64. Can you try:

    conda search gala --channel conda-forge

and tell me what the output says?

You may also just be able to install it with:

    conda install --channel conda-forge gala

**Comment by jortiz12** [comment]
First of all, many thxs for the assistnace.
1.- Yes, tring the installation on a windows-based machine
2.- `conda search gala --channel conda-forge` works!!!!
![imagen](https://user-images.githubusercontent.com/2719866/140080925-60105641-386a-4694-b80f-c7a81f2189c6.png)
3.- However, when running thos line of code `import gala.coordinates as gc`, it throws the following error
`ImportError: DLL load failed: No se puede encontrar el módulo especificado.`
(transaltion: "It can't be found the specified module"

Thxs again
Jose

**Comment by jortiz12** [comment]
Hello again,
After updating, reinstalling, etc, conda (and anaconda), no luck when running
`conda install --channel conda-forge gala`
It gets trapped into solving environment, failing to install it.
![imagen](https://user-images.githubusercontent.com/2719866/140181939-700d7fd7-b246-41d9-9c0c-3338c7b1409e.png)

**Comment by jortiz12** [comment]
Hello Adrian,
Have been trying various alternatives but no luck.
The installation gets "frozen".
Once again, thanks for the assistance.
Jose

**Comment by adrn** [comment]
Hi Jose,
I don't have any ideas here because I don't have access to a windows machine to test, sorry! However, gala does install on windows in github actions runs. Here is what works for my tests on windows:
```
conda install -c conda-forge -q gsl libpython
pip install git+https://github.com/adrn/gala
```
