### ISSUE TITLE
Flattened NFW never used? 

### ISSUE THREAD

**Issue by balbinot** [adrn/gala#254]
It seems that the builtin potential wrapper FlattenedNFWWrapper is not used when setting c!=1 in NFWPotential().

See example below
https://gist.github.com/balbinot/94d42b9ed1d9dc2e9ceffff2e1ac35fb

When calling NFW with c!=1 it seems to fall back to c=1 case, even when a and b are != 1

Using version 1.4.1, installed via conda (conda-forge) on Linux.

**Comment by adrn** [comment]
Ack, thanks for the report! Will take a look ASAP.
