### ISSUE TITLE
[Feature Request] Add `.pre-commit-config.yml`

### ISSUE THREAD

**Issue by SauravMaheshkar** [adrn/gala#256]
I noticed that most of (if not all) the steps of the Contributing wiki can be automated via [**pre-commit**](https://pre-commit.com/). Having [**pre-commit**](https://pre-commit.com/) would make that process much easier and enforce that the developers follow coding conventions.

I'd be more than happy to take this up.

**Comment by adrn** [comment]
Hi @SauravMaheshkar - I'm potentially interested! Which Contributing wiki are you referring to?

**Comment by SauravMaheshkar** [comment]
I was referring to this [**Developer Documentation**](http://gala.adrian.pw/en/latest/contributing.html#developer-documentation)
