### ISSUE TITLE
Inputting Spherical Initial Coordinates into Gala

### ISSUE THREAD

**Issue by juliaespositon** [adrn/gala#275]
Hi,

I was wondering whether it's possible to use spherical coordinates, specifically in the line: ics = gd.PhaseSpacePosition(pos = position, vel = velocity).  I tried doing this, but ran into an issue with trying to create a velocity quantity array with the units rad/s, rad/s, and km/s. If that is not possible, is there a way to use gala to convert spherical velocities to cartesian velocities?

Thank you!
Julia

**Comment by adrn** [comment]
Hi @juliaespositon - yes it is possible! Just to make sure I understand: You have r, phi, theta and dr/dt, dphi/dt, dtheta/dt, and you'd like to use those quantities to initialize a `PhaseSpacePosition` object? If that is right, you can do this:

```python
import astropy.coordinates as coord
import astropy.units as u
import numpy as np
import gala.dynamics as gd

pos = coord.PhysicsSphericalRepresentation(
    r=[10., 5.] * u.kpc,
    phi=[11., 271] * u.deg,
    theta=[31., 77] * u.deg
)

vel = coord.PhysicsSphericalDifferential(
    d_r=[105, -18] * u.km/u.s,
    d_phi=[2., 0.5] * u.mas/u.yr,
    d_theta=[-1., -3.] * u.mas/u.yr
)

ics = gd.PhaseSpacePosition(pos=pos, vel=vel)
```

**Comment by juliaespositon** [comment]
Thank you so much!!
Julia
    On Thursday, April 21, 2022, 08:20:41 PM EDT, Adrian Price-Whelan ***@***.***> wrote:  
 
 


Hi @juliaespositon - yes it is possible! Just to make sure I understand: You have r, phi, theta and dr/dt, dphi/dt, dtheta/dt, and you'd like to use those quantities to initialize a PhaseSpacePosition object? If that is right, you can do this:
import astropy.coordinates as coord
import astropy.units as u
import numpy as np
import gala.dynamics as gd

pos = coord.PhysicsSphericalRepresentation(
    r=[10., 5.] * u.kpc,
    phi=[11., 271] * u.deg,
    theta=[31., 77] * u.deg
)

vel = coord.PhysicsSphericalDifferential(
    d_r=[105, -18] * u.km/u.s,
    d_phi=[2., 0.5] * u.mas/u.yr,
    d_theta=[-1., -3.] * u.mas/u.yr
)

ics = gd.PhaseSpacePosition(pos=pos, vel=vel)
