### ISSUE TITLE
Matrix multiplication in transform_pm_cov 

### ISSUE THREAD

**Issue by HNLala** [adrn/gala#289]
https://github.com/adrn/gala/blob/46343c4163531f5f1e4f196ae6d58cbfcc6921a4/gala/coordinates/pm_cov_transform.py#L133
 
Should the indices here be:
``` np.einsum('nij, nkj->nik', cov, G)) ```
so as to match the $G C G^T$ as shown in Gaia [documentation](https://gea.esac.esa.int/archive/documentation/GDR2/Data_processing/chap_cu3ast/sec_cu3ast_intro/ssec_cu3ast_intro_tansforms.html#SSS1.P1)?

Since, C is symmetric, this doesn't affect the outcome; however, it might speed up the computation ever so slightly?

**Comment by HNLala** [comment]
Yes, I'd be happy to do it.

**Comment by adrn** [comment]
Closed by #292
