### ISSUE TITLE
Build against numpy 2

### ISSUE THREAD

**Issue by nstarman** [adrn/gala#381]
I think gala needs to be built against numpy 2.0.

Note sure if this is a permalink: https://productionresultssa9.blob.core.windows.net/actions-results/c9037bd6-1666-411b-8483-ecfad96b210e/workflow-job-run-92eb5d10-4f44-58ce-6977-4ccd53e44d4b/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-06-30T15%3A34%3A10Z&sig=rwUMCq9JmFm612XhK%2FVPHN%2BVMwPyBhomNAwbYgLOz4c%3D&ske=2024-07-01T02%3A59%3A45Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-06-30T14%3A59%3A45Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-06-30T15%3A24%3A05Z&sv=2023-11-03

**Comment by adrn** [comment]
Yes, definitely! I just haven't had time to sort it out :) 👶 🍼

**Comment by adrn** [comment]
Cutting a release today to sort this out!

**Comment by adrn** [comment]
Release is out on pypi (1.9.0)
