### ISSUE TITLE
Question on Hessian of potential

### ISSUE THREAD

**Issue by syrte** [adrn/gala#85]
Hessian for potential $\Phi(\vec {r})$ is $\nabla\nabla \Phi$, i.e. ∂∂Φ/∂xi/∂xj right?

If I understand correctly,  `np.diag(om)` in 
```
class HarmonicOscillatorPotential(PotentialBase):
    ...
    def _hessian(self, q, t=0.):
        om = np.atleast_1d(self.parameters['omega'])
        return np.tile(np.diag(om)[:,:,None], reps=(1,1,q.shape[0]))
```
should be `np.diag(om*2)`?

Sorry if I missed anything obvious.

**Comment by adrn** [comment]
Wow, this must be a record for longest time before response - really sorry about that. I think you're right, if you mean `om**2`? Are you still interested in contributing that fix? :)
