### ISSUE TITLE
Pronunciation?

### ISSUE THREAD

**Issue by jradavenport** [adrn/gala#87]
How do you pronounce "Gala"? 

"Gay-la", like the apple?

"Gal-la", short for "galaxy"

"Ga-lah", I don't even know why...

**Comment by jradavenport** [comment]
You can see I'm asking this real important Q's here...

**Comment by adrn** [comment]
"Gal-la", short for "galaxy"! Should I add the IPA to the docs? Is this right: "ɡælæ"?

**Comment by jradavenport** [comment]
Why is there not "IPA audio as a service" for new words?!

I think it's "ɡælə", shortening from [this link](https://en.wiktionary.org/wiki/galaxy)
