### ISSUE TITLE
Sphinx build is failing now?

### ISSUE THREAD

**Issue by adrn** [adrn/gala#98]
@bsipocz any idea why the sphinx build is failing now? It claims to fail because of 6 warnings, but I don't see any Sphinx warnings -- I see 12 (expected) warnings from the code executed in some of the documentation.

https://travis-ci.org/adrn/gala/jobs/273881696

**Comment by bsipocz** [comment]
Sphinx became much more picky about the warnings in 1.6+, so we used to centrally limit the version to 1.5.6 that I lifted last week.
So I expect the quickest workaround is to add ``SPHINX_VERSION=1.5.6`` to the docs build in ``.travis.yml``. Long term solution would be to deal with those warnings in your docs.

**Comment by adrn** [comment]
Thanks!
